# Generated by Django 4.0.5 on 2022-07-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageDam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damName', models.TextField()),
                ('damLocation', models.TextField()),
                ('damHeight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ManageDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.TextField()),
                ('departmentCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ManageStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.IntegerField()),
                ('staffname', models.TextField()),
                ('staffEmail', models.EmailField(max_length=254)),
                ('staffImage', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
