# Generated by Django 4.0.5 on 2022-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0002_managecredit_managefish_managesales_managetimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managestaff',
            name='staffImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
