# Generated by Django 4.0.5 on 2022-07-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0003_alter_managestaff_staffimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managestaff',
            name='staffImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='managestaff',
            name='staffid',
            field=models.CharField(max_length=50),
        ),
    ]
