# Generated by Django 4.0.5 on 2022-07-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0005_alter_managestaff_staffimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managestaff',
            name='staffImage',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
