# Generated by Django 4.0.5 on 2022-07-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0006_alter_managestaff_staffimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageStaff',
        ),
    ]
