# Generated by Django 4.0.5 on 2022-07-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0007_delete_managestaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=50)),
                ('staffname', models.TextField()),
                ('staffEmail', models.EmailField(max_length=254)),
                ('staffImage', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
