# Generated by Django 4.0.5 on 2022-07-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0008_managestaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageSales',
        ),
    ]
