# Generated by Django 4.0.5 on 2022-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0009_delete_managesales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishSales', models.FloatField()),
                ('salesDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ManageTimeline',
        ),
    ]
