# Generated by Django 4.0.5 on 2022-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0010_managesales_delete_managetimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvestTime', models.DateField()),
                ('fishType', models.TextField()),
            ],
        ),
    ]
