# Generated by Django 4.0.5 on 2022-07-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0011_managetimeline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageSales',
        ),
    ]
